### ISSUE TITLE
Is there any possible way to get POSCAR file from Materials Project through MPRester?

### ISSUE THREAD

**Issue by 755452800** [materialsproject/workshop#109]
Hi,

Thanks for your great work in these workshops.

Recently I was using pymatgen and MPI conducting some VASP calculation. For POSCAR file generation, I used **MPRester()** method to get the data of a specific material and write value 'cif' to a cif file and then using Poscar method to create a POSCAR file:
```
    with MPRester() as mpr:
        material = mpr.get_data('element')
        for item in material:
            if item['formation_energy_per_atom'] == 0.0:
                cif_name = element + '.cif'
                f_cif = open(cif_name, 'w+')
                f_cif.write(item['cif'])
                f_cif.close()
    struc = Structure.from_file(cif_name)
    Poscar(structure=struc).write_file('POSCAR') 
```
However, I found the POSCAR file generated this way is different from the POSCAR file downloaded directly from Materials Project. In a specific case, Ir (mp-101), VASP calculation failed on the basis of the POSCAR generated by the way mentioned above, but worked perfectly on the basis of the downloaded POSCAR file.

So I was wondering if there is a API way that we can get the POSCAR directly.

**Comment by mkhorton** [comment]
Request the `structure` and use the `Structure.to("POSCAR")` method would be my advice.

**Comment by 755452800** [comment]
Thank you for your advice ! According to your advice, the code was rewrite as: 
```
with MPRester() as mpr:
    material = mpr.get_data('Ir')
    for item in material:
        if item['formation_energy_per_atom'] == 0.0:
            print(item['material_id'])
            struc = mpr.get_structure_by_material_id(item['material_id'])
            struc.to(fmt='poscar', filename='POSCAR')
```
(I'm not sure how to request the `structure` from Materials Project, and after reading the api docs I think I may use `get_structure_by_material_id` , is that the right way?)

And it's seems that  the method `get_structure_by_material_id` still got the one single atom Ir structure, which is still different from the POSCAR file downloaded from the Materials Project (four Ir atoms structure). (I think the one atom Ir structure is the primitive cell structure of Ir, and this structure leads to a VASP calculation failure unless change the algorithm to ALGO = Old VeryFast)

Any advice ? Did I use the wrong way requested the wrong `structure` ?

**Comment by shyamd** [comment]
I would ask this on matsci.org. This repo gets very little direct views outside of organizing and running the workshop.

**Comment by 755452800** [comment]
> I would ask this on matsci.org. This repo gets very little direct views outside of organizing and running the workshop.

Thanks for your suggestion.
