### ISSUE TITLE
2021 Basic Python Lesson Updates

### ISSUE THREAD

**Issue by kdfong** [materialsproject/workshop#133]
Unclear Concepts:

- The example on importing and using numpy and matplotlib introduces too much new content at once, and there isn’t sufficient time for the students to actually understand it. I would simplify this example. 
- The exercise “Copying (or Not)” on mutability was too rushed. I would suggest removing this example and spending more time on the for loop exercises. 
- There are some small references to topics covered in the next lesson or not covered at all, for example the pow() function, setting default arguments in functions, and if statements. I would try to minimize these where possible.

Missing:

- How and why to add comments to your code
- I would move the section on indentation from the Advanced Python lesson to this lesson, when for loops are introduced
- The section on modifying lists could be expanded by adding discussion of the + operator, * operator, and list comprehension.

**Comment by shyamd** [comment]
These all look good. For the next week can you submit a PR that takes care of the unclear things you highlighted? I agree removing the "Copying (or Not)" example is a good idea. It's confusing and not that relevant for the level of python that people will need.
