### ISSUE TITLE
2021 Advanced MongoDB Lesson Comments

### ISSUE THREAD

**Issue by sivonxay** [materialsproject/workshop#134]
# *Unclear Concepts*
- When using a sort operation while querying, it is unclear how documents are sorted when the sort key is a list. 
    - i.e. when given the docs: [{'prize': [{'year': 1964}, {'year': 1967}]}, {'prize': [{'year': 1968}, {'year': 1963}]}, {'prize': [{'year': 1965}, {'year': 1972}]}], what will the sort look like? Does it use the first item in the list or does it sort the list first?
- When is it disadvantageous to use add indexes to collections.
    - Are there certain data types (such as binary string) that would not be useful to have an index for?
    - Do indexes speed up regex operations?
    - Why not index everything? 
    
# *Potentially Missing Concepts*
- Could touch on other mongodb operators such as $size and $all (currently only $elemMatch).
- Updating or inserting documents (insert_one(), update_one(), insert_many(), update_many())
- Mongo aggregation - a quick intro. Showing taught concepts and using aggregation

**Comment by mkhorton** [comment]
One thing this lesson might need is an appropriate segue or justification for why we're teaching this. The reasons we teach this are clear for anyone who uses FireWorks, atomate, etc., but we don't teach these extensively in the virtual format, so it may be unclear to attendees. Last year, it tied in nicely with the `MPRester.query({})` syntax but this will not be present in this year's lesson (due to updates from @munrojm).

**Comment by sivonxay** [comment]
Ah yes, I agree with @mkhorton. It feels like the advanced mongodb primer is a bit disconnected from the materials science/ MP. It jumps into the topics without justifying the context in which it's useful. Even as someone who uses mongodb daily, I find it difficult to imagine a matsci use for some of them. Perhaps this is by design, since this is a primer rather than a workshop core lesson.

My suggestion would have been to replace the Nobel Laureates collection with some sort of materials property collection, but that may be too big a change as we are 1 month out. Working with what we have, an appropriate justification/intro would probably be sufficient.

**Comment by munrojm** [comment]
I agree with @mkhorton on this. Since the new API that we are teaching involves zero usage of MongoDB query operator syntax, we may want to restructure.

**Comment by shyamd** [comment]
This is a good point. We could switch to focusing on something like pandas data frames? Are there other concepts people think will jive better?

**Comment by shyamd** [comment]
Done!
