### ISSUE TITLE
Intro to pymatgen comments 

### ISSUE THREAD

**Issue by ruoxiyangxixi** [materialsproject/workshop#135]
Confusing parts: 

- Species properties, are they freely definable or stored properties? 
- Constructing composition, what does the '50% Au 50% Cu' mean?  

New components potentially useful: 

- Non-linear molecule construction, where bond angle is input parameter
- After supercell transformation, create deformation structure 
- Create vacancy defect to structure

**Comment by shyamd** [comment]
Looks good @ruoxiyangxixi 

Can you implement a PR that fixes the two confusing parts for this coming week. Please make a new section to address the species property in the lesson.
