### ISSUE TITLE
2021 Advanced Python Lesson Comments

### ISSUE THREAD

**Issue by mjwen** [materialsproject/workshop#140]
### Unclear/confusing
- Various ways to do if statement and their application case, using `==`, `<`, `in`, `is None`, etc.
- Use before introduction
- Syntax of the data structures, e.g. a function starts with keyword `def`... 
- How to loop over `set`, `dict`. e.g. the difference between lopping over `dict` and  `dict.items()`

### Missing/redundant
- The discussion of `set` can be be fully removed; it's nice on its own but it's not connected to other parts and we don't use it that often throughout the workshop lessons 
- Add very brief discussion of class, no mentioning of inheritance and such. Class is so central to pymatgen and it is already used in the exercise  
- Discuss typing and documentation for function and class

**Comment by shyamd** [comment]
Sounds good. The first three sound like important updates that should be tackled now. The last modification on how to loop over set or dict might be a bit advanced. Can we move that to the missing/redundant section and add to next week's todos?

For this week, can you try and implement fixes for the other unclear/confusing points you've highlighted in a PR?
