### ISSUE TITLE
2021 Materials Project Website Comments

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/workshop#141]
**Things that are confusing**
- Attendees may need an explanation of what the ICSD is (e.g. when discussing the "experimentally observed" flag)
- Detail about elasticity data for dynamically unstable materials may be a little too much "in the weeds" for the walkthrough
- A little confusing what kind of data users can expect to find in Battery and Molecules explorers that they won't find in the Materials Explorer
- The similarity of the task page to the detail page may confuse attendees. Maybe showing multiple task pages would help? Maybe showing none at all?

**Things to add**
- Demonstration of advanced searching features
  - Wildcard searches
  - Chemical system vs. elements searches
- Description of the overall structure of the detail page
- Discussion about transition to the new website
- How workshop attendees can provide feedback on the new website
  - Perhaps a separate curated forum just for collecting this kind of feedback

**Comment by shyamd** [comment]
Looks good. All of your modifications look good. For the last point on the similarity of the tasks page, I mostly agree. This might be too in the weeds and we would be better off just not talking about it.

One thing to remember is that the actual workshop lesson time will never be enough to cover all the topics. We can leave extra material in there for people to peruse on their own time.
