### ISSUE TITLE
2021 Reaction Networks / Exploring New Systems Comments

### ISSUE THREAD

**Issue by mattmcdermott** [materialsproject/workshop#143]
At the 2021 MP Workshop, the "Reaction Networks" lesson will replace the previous year's "Exploring New Systems" lesson. I will be taking some bits from the previous lesson and also adding many new concepts.

*Confusing concepts*
- Some of the trickier phase diagram concepts were very quickly explained... what is "energy above hull" and connection with metastability? How is this related to chemical potential/predominance diagrams and why is any of this useful in synthesis?
- How does a compound phase diagram differ from an interface reaction diagram?
- How do you put a disordered structure on the phase diagram? i.e. what do you do after you run a bunch of disordered->ordered structures? How do we compare alloy structures to MP structures?

*Things to keep* 
- Querying MPRester for ComputedEntry objects within specific systems, based on  more advanced element and target criteria
- Building of DataFrames for examining the energetics of various targets / reactions
- Exploration of the various types of phase diagrams and why you might use them (i.e. how they relate to synthesis)

*Things to add*
- Use of interface reaction calculator for predicting most likely reactions
- Chemical potential diagrams
- Enumerators for assessing possible reactions
- Reaction networks and coming up with possible balanced reaction pathways

**Comment by mkhorton** [comment]
> Querying MPRester for ComputedEntry objects within specific systems, based on more advanced element and target criteria

Make sure to co-ordinate with @munrojm on this, since we're teaching the new MPRester this year.

**Comment by shyamd** [comment]
Done!
