### ISSUE TITLE
2021 Intro to MongoDB 

### ISSUE THREAD

**Issue by arepstein** [materialsproject/workshop#147]
**Confusing or unclear**

- What is MongoDB? Where is it hosted?

** Additions**

 - $regex operator for basic text searches. No actual regex syntax necessary. 
 - Introduce where the database we're using is hosted and briefly explain how someone could locally host a database.

**Comment by shyamd** [comment]
Ah! Took a long time to get to this. Looks good. I'd recommend against going too far into hosting one's own database. It's not hard, but it's also a rabbit hole. Hihg level such as: "You can host it yourself or buy some access at an online provider such as MongoDB Atlas, Azure CosmosDB, or Amazon DocumentDB." would be my recommendation.
