### ISSUE TITLE
2021 Matminer/Machine Learning Comments

### ISSUE THREAD

**Issue by ardunn** [materialsproject/workshop#148]
## Confusing
- Some small typos/miswordings such as the `semiconductor_df` cells
- `citations` method footnote does not show an example of how to use it, but it is very important
- Part 3 of the notes does not give an overview of the ML model we will be creating, it just dives right into fitting a model
- The Automatminer part at the end both does not work with the newest matminer *and* seems "tacked on" to an already long lesson *and* does not have corresponding exercises...

## To add
- an example of `citations`
- add a _brief_ explanation into Part 3 of the overall goal (fitting a model to predict bulk moduli)
- Some mention of matbench, perhaps @mkhorton could direct how to proceed here

## Other
- Matminer notebook uses outdated version of matminer/must be updated to 0.7.2 as there were breaking changes in 0.7.3
- Additionally with Figrecipes, as it is now its own repo - might be worth just using plotly express instead? Alternatively I can make Figrecipes its own pypi package and add it to the requirements...

**Comment by shyamd** [comment]
Thanks @ardunn 

Agreed on removing figrecipes. I think plotly express effectively does what figrecipes intended no?

I think removing automatminer is perfectly fine, especially if that can be replaced with more interactivity.
