### ISSUE TITLE
Can I upload the video in youtube to Chinese video platform?

### ISSUE THREAD

**Issue by hitliaomq** [materialsproject/workshop#80]
Hello,

I'm a joint phd studet([PSU ](https://www.psu.edu/) with [HIT](http://www.hit.edu.cn/)) from China. I notice that there are some wonderful videos about the workshop in youtube. However, in China, we can't log in youtube.

So can I upload these workshop videos to some Chinese video platform(e.g. [Bilibili](https://www.bilibili.com/)). Of course, all copyrights belongs to the MP developers and I will give the original link to youtube, this github reposite and MP's website.

Bests
Mingqing Liao

**Comment by shyamd** [comment]
Yes. That is fine with everyone involved. Please provide a link in this Issue once posted and I'll include that in the workshop docs itself.

**Comment by hitliaomq** [comment]
@shyamd Thank you for your kind agreement. After I uploaded to the website, I will provide the link here. Thank you again.

**Comment by hitliaomq** [comment]
Hello, @shyamd 

I have uploaded the videos to Bilibili. Below is the link. The original link and the link of this repository is given in the introduction, and if the introduction is inappropriate, please let me know and I will change it.

https://www.bilibili.com/video/BV1Uz4y1f7L5/

Thank you very much.

Best regards
Mingqing

**Comment by shyamd** [comment]
Thanks. I've updated the main page to include that link.
